# Generated by Django 3.2.7 on 2021-09-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood_watch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='bio', max_length=20)),
                ('hood', models.CharField(default='hood', max_length=20, null=True)),
                ('profile_pic', models.ImageField(blank=True, default=0, upload_to='images/profiles/')),
                ('email', models.EmailField(blank=True, default='email', max_length=254)),
                ('contact', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
