# Generated by Django 3.2.7 on 2021-09-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood_watch', '0006_auto_20210929_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='hood_photo',
            field=models.ImageField(null=True, upload_to='images/hoods/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, default='email', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default=0, null=True, upload_to='images/profiles/'),
        ),
    ]
